routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/units', 'UnitController@index');
Route::get('/units/{unit_id}', 'UnitController@show')->name('unit.show');;

Route::get('/leases', 'LeaseController@index');
Route::get('/contacts', 'ContactController@index');
Route::get('/invoices', 'InvoiceController@index');

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    public function invoicedEntity()
    {
        return $this->morphTo();
    }

    public function entitySpecificAttributes()
    {
        return $this->hasMany('App\Models\InvoiceAttribute');
    }

    public function getStatusAttribute($value) {
        return ucfirst($value);
    }

    public function getInvoicedEntityTypeAttribute($value) {
        return ucfirst($value);
    }

    public function getInvoicedAmountAttribute($value) {
        return number_format($value, 2);
    }

}

app/Models/Lease.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lease extends Model
{
    //
    public function unit()
    {
        return $this->belongsTo('App\Models\Unit');
    }

    public function getStartDateAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('d-m-Y');
    }

    public function getEndDateAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('d-m-Y');
    }

    public function getRentAttribute($value) {
        return number_format($value);
    }

    public function invoices()
    {
        return $this->morphMany('App\Models\Invoice', 'invoiced_entity');
    }
}

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    public function leases()
    {
        return $this->hasMany('App\Models\Lease');
    }

    public function getGuideRentalAmountAttribute($value) {
        return number_format($value);
    }

    public function invoices()
    {
        return $this->morphMany('App\Models\Invoice', 'invoiced_entity');
    }

}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Unit;
use Illuminate\Http\Request;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $units = Unit::withCount('invoices','leases')->paginate(5);
        return view('units', ['units' => $units]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $unit_id)
    {
        $unit = Unit::with(['invoices', 'invoices.entitySpecificAttributes'])->findOrFail($unit_id);
        return view('unit', ['unit' => $unit]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unit $unit)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Unit $unit)
    {
        //
    }
}

resources/views/contacts.blade.php
@extends('layouts.app')
    @section('bodyClass') contacts-page @endsection
@section('content')
    <h2>Contacts</h2>
    <div class="container">
        <div class="text-right">
            Total No. of Contacts : {{ $contacts->total() }}
        </div>
        <ul class="list-group list-group-flush">
            @foreach ($contacts as $contact)
                <li class="list-group-item row">
                    <div class="col-md-6">
                        First Name: {{ $contact->first_name }}<br />
                        Last Name: {{ $contact->last_name }}<br />
                        Email: {{ $contact->email }}<br />
                    </div>
                </li>
            @endforeach
        </ul>
        <br />
        {{ $contacts->links() }}
    </div>
@endsection

resources/views/invoices.blade.php
@extends('layouts.app')
    @section('bodyClass') contacts-page @endsection
@section('content')
    <h2>Invoices</h2>
    <div class="container">
        <div class="text-right">
            Total No. of Invoices : {{ $invoices->total() }}
        </div>
        <ul class="list-group list-group-flush">
            @foreach ($invoices as $invoice)
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="col-md-12">
                        Invoice #: {{ $invoice->id }} <br />
                        Status : {{ $invoice->status }} <br />
                        Amount : AED {{ $invoice->invoiced_amount }} <br />
                        Due Date : {{ $invoice->due_date }} <br />
                        Invoice For : {{ $invoice->invoiced_entity_type }}<br />
                        @if ($invoice->entitySpecificAttributes)
                        <strong>{{ $invoice->invoiced_entity_type }} Specific Invoice Data</strong> <br />
                            <ul>
                            @foreach ($invoice->entitySpecificAttributes as $additionalAttribute)
                                <li>{{ $additionalAttribute->fieldAtrribute->field_name }} : {{ $additionalAttribute->field_value }}</li>
                            @endforeach
                            </ul>
                        @endif
                        {{ $invoice->invoiced_entity_type }} Details :
                        <div class="col-md-8">
                            <ul>
                                @switch($invoice->invoiced_entity_type)
                                    @case('Unit')
                                        <li>Unit Id: {{ $invoice->invoicedEntity->id }}</li>
                                        <li>Unit Number: {{ $invoice->invoicedEntity->unit_no }}</li>
                                        <li>Size: {{ $invoice->invoicedEntity->size }}</li>
                                        <li>Rent: AED {{ $invoice->invoicedEntity->guide_rental_amount }}</li>
                                        @break

                                    @case('Lease')
                                        <li>Lease Id: {{ $invoice->invoicedEntity->id }}</li>
                                        <li>Rent: AED {{ $invoice->invoicedEntity->rent }}</li>
                                        <li>Start Date: {{ $invoice->invoicedEntity->start_date }}</li>
                                        <li>End Date: {{ $invoice->invoicedEntity->end_date }}</li>
                                        @break

                                    @default
                                        <li>Contact Id: {{ $invoice->invoicedEntity->id  }}</li>
                                        <li>First Name: {{ $invoice->invoicedEntity->first_name }}</li>
                                        <li>Last Name: {{ $invoice->invoicedEntity->last_name }}</li>
                                        <li>Email: {{ $invoice->invoicedEntity->email }}</li>
                                @endswitch
                            </ul>
                        </div>
                    </div>
                </li>
            @endforeach
        </ul>
        <br />
        {{ $invoices->links() }}
    </div>
@endsection

resources/views/leases.blade.php
@extends('layouts.app')
    @section('bodyClass') leases-page @endsection
@section('content')
    <h2>Leases</h2>
    <div class="container">
        <div class="text-right">
            Total No. of Leases : {{ $leases->total() }}
        </div>
        <ul class="list-group list-group-flush">
            @foreach ($leases as $lease)
                <li class="list-group-item row">
                    <div class="col-md-6">
                        Lease Id: {{ $lease->id }}<br />
                        Rent: AED {{ $lease->rent }}<br />
                        Start Date: {{ $lease->start_date }}<br />
                        End Date: {{ $lease->end_date }}<br />
                    </div>
                    <div class="col-md-6">
                        Unit Number: {{ $lease->unit->unit_no }}<br />
                        Unit Id: {{ $lease->unit->id }}<br />
                    </div>
                </li>
            @endforeach
        </ul>
        <br />
        {{ $leases->links() }}
    </div>
@endsection

resources/views/unit.blade.php
@extends('layouts.app')
    @section('bodyClass') unit-page @endsection
@section('content')
    <h2>Unit</h2>
    <div class="container">

        <ul class="list-group list-group-flush">
            <div class="col-md-6">
                Unit Id: {{ $unit->id }}<br />
                Unit Number: {{ $unit->unit_no }}<br />
                Size: {{ $unit->size }}<br />
                Rent: AED {{ $unit->guide_rental_amount }}<br />
            </div>
        </ul>
        <div class="d-flex p-2">Invoices</div>
            @if ($unit->invoices)
                <ul class="list-group list-group-flush">
                    @foreach ($unit->invoices as $invoice)
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="col-md-12">
                                Invoice #: {{ $invoice->id }} <br />
                                Status : {{ $invoice->status }} <br />
                                Amount : AED {{ $invoice->invoiced_amount }} <br />
                                Due Date : {{ $invoice->due_date }} <br />
                                @if ($invoice->entitySpecificAttributes)
                                    <strong>{{ $invoice->invoiced_entity_type }} Specific Invoice Data</strong>
                                    <ul>
                                        @foreach ($invoice->entitySpecificAttributes as $additionalAttribute)
                                            <li>{{ $additionalAttribute->fieldAtrribute->field_name }} : {{ $additionalAttribute->field_value }}</li>
                                        @endforeach
                                    </ul>
                                @endif
                            </div>
                        </li>
                    @endforeach
                </ul>
            @else
                No Invoices Found.
            @endif
    </div>
@endsection

resources/views/units.blade.php
@extends('layouts.app')
    @section('bodyClass') units-page @endsection
@section('content')
    <h2>Units</h2>
    <div class="container">
        <div class="text-right">
            Total No. of Units : {{ $units->total() }}
        </div>
        <ul class="list-group list-group-flush">
            @foreach ($units as $unit)
                <li class="list-group-item">
                    <div class="col-md-6">
                        Unit Id: {{ $unit->id }}<br />
                        Unit Number: {{ $unit->unit_no }}<br />
                        Size: {{ $unit->size }}<br />
                        Rent: AED {{ $unit->guide_rental_amount }}<br />
                        No. Of Invoices : {{$unit->invoices_count}}<br />
                        No. Of Leases : {{$unit->leases_count}}
                    </div>
                    <div class="col-md-12 text-right">
                        <a href="{{ route('unit.show', ['unit_id' => $unit->id]) }}"><i class="fa fa-receipt"></i> View Property & Invoices Details</a>
                    </div>
                </li>
            @endforeach
        </ul>
        <br />
        {{ $units->links() }}
    </div>
@endsection